# -*- coding: utf-8 -*-
"""Profissão Analista de dados M2 Exercício(Davi).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svL8KYZkJzRWGfIIT2ZzDQtbPY_ue_zO

<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Python: Estruturas de Dados
Caderno de **Exercícios**<br> 
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Listas;</li>
  <li>Conjuntos;</li>
  <li>Dicionários.</li>
</ol>

---

# **Exercícios**

## 1\. Listas

Criei uma lista chamada `filmes` com o nome dos 10 primeiros filmes mais bem avaliados no site no [IMDB](https://www.imdb.com/chart/top/). Imprima o resultado.
"""

filmes = [
    'Um Sonho de Liberdade',
    'O Poderoso Chefão',
    'Batman: O Cavaleiro das Trevas',
    'A Lista de Schindler',
    '12 Homens e uma Sentença',
    'O Poderoso Chefão II',
    'O Senhor dos Anéis: O Retorno do Rei',
    'Pulp Fiction: Tempo de Violência',
    'A Origem',
    'Forrest Gump: O Contador de Histórias'
]

qt_elementos = len(filmes)
print(filmes)
print(qt_elementos)

"""Simule a movimentação do *ranking*. Utilize os métodos `insert` e `pop` para trocar a posição do primeiro e do segundo filme da lista. Imprima o resultado.


"""

# Removendo o primeiro e segundo elemento da lista com o mesmo código pois, ao remover o 1º, o antigo 2º passa a ser o 1º
primeiro_filme = filmes.pop(0)
primeiro_filme = filmes.pop(0)

# Adicionando os novos elementos com as posições invertidas

filmes.insert(0,'O Poderoso Chefão')
filmes.insert(1,'Um Sonho de Liberdade')

qt_elementos = len(filmes)
print(filmes)
print(qt_elementos)

"""---

## 2\. Conjuntos

Aconteceu um erro no seu *ranking*. Simule a duplicação dos três últimos filmes da lista. Imprima o resultado.
"""

# Simulando a diplicação atravéz do método 'insert'

filmes.insert(10,'Forrest Gump: O Contador de Histórias') 
filmes.insert(9, 'A Origem')
filmes.insert(8, 'Pulp Fiction: Tempo de Violência')

print(filmes)

"""Utiliza a conversão `set` e `list` para remover os valores duplicados. Imprima o resultado. """

# Convertendo para conjunto a fim de eliminar as duplicatas.

conjunto_de_filmes = set(filmes)

print(conjunto_de_filmes)
print(type(conjunto_de_filmes))

# Transformando o conjunto em lista novamente.

filmes = list(conjunto_de_filmes)

print(filmes)
print(type(filmes))

"""---

## 3\. Dicionários

Repita os exercícios da parte 1 (listas). Os elementos da lista `filmes` devem ser dicionários no seguinte formato: `{'nome': <nome-do-filme>, 'ano': <ano do filme>, 'sinopse': <sinopse do filme>}`.
"""

filmes = {
    'nome1':'Um Sonho de Liberdade', 'ano1': 1994, 'sinopse1': 'Ao longo de vários anos, dois condenados formam uma amizade, buscando consolo e, eventualmente, redenção por meio da compaixão básica.',
    'nome2':'O Poderoso Chefão', 'ano2': 1972, 'sinopse2': 'Don Vito Corleone, chefe de uma família mafiosa, decide entregar seu império a seu filho mais novo, Michael. No entanto, sua decisão involuntariamente coloca a vida de seus entes queridos em grave perigo.',
    'nome3':'Batman: O Cavaleiro das Trevas', 'ano3': 2008, 'sinopse3': 'Quando a ameaça conhecida como Coringa causa estragos e caos no povo de Gotham, Batman deve aceitar um dos maiores testes psicológicos e físicos de sua capacidade de lutar contra a injustiça.',
    'nome4':'A Lista de Schindler', 'ano4': 1993, 'sinopse4': 'Na Polônia ocupada pelos alemães durante a Segunda Guerra Mundial, o industrial Oskar Schindler gradualmente se preocupa com sua força de trabalho judaica depois de testemunhar sua perseguição pelos nazistas.',
    'nome5':'12 Homens e uma Sentença', 'ano5': 1957, 'sinopse5': 'O júri em um julgamento de assassinato na cidade de Nova York é frustrado por um único membro cuja cautela cética os obriga a considerar as evidências com mais cuidado antes de pular para um veredicto apressado.',
    'nome6':'O Poderoso Chefão II', 'ano6': 1974, 'sinopse6': 'O início da vida e a carreira de Vito Corleone na cidade de Nova York dos anos 1920 são retratados, enquanto seu filho, Michael, expande e aumenta seu controle sobre o sindicato do crime familiar.',
    'nome7':'O Senhor dos Anéis: O Retorno do Rei', 'ano7': 2003, 'sinopse7': 'Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron para desviar seu olhar de Frodo e Sam enquanto eles se aproximam do Monte da Perdição com o Um Anel.',
    'nome8':'Pulp Fiction: Tempo de Violência', 'ano8': 1994, 'sinopse8': 'As vidas de dois assassinos da máfia, um boxeador, um gângster e sua esposa e uma dupla de bandidos se entrelaçam em quatro histórias de violência e redenção.',
    'nome9':'A Origem', 'ano9': 2010, 'sinopse9': 'Um ladrão que rouba segredos corporativos por meio do uso da tecnologia de compartilhamento de sonhos recebe a tarefa inversa de plantar uma ideia na mente de um CEO, mas seu passado trágico pode condenar o projeto e sua equipe ao desastre.',
    'nome10':'Forrest Gump: O Contador de Histórias', 'ano10': 1994, 'sinopse10': 'As presidências de Kennedy e Johnson, a Guerra do Vietnã, o escândalo de Watergate e outros eventos históricos se desenrolam na perspectiva de um homem do Alabama com um QI de 75, cujo único desejo é reencontrar sua namorada de infância.'
}

print(filmes)
print(type(filmes))

